-- ============================================================
-- Tournaments Feature
-- ============================================================

-- ------------------------------------------------------------
-- 1. Add `cancelled` to existing game_status enum
--    (needed for terminating pending games when tournament starts)
-- ------------------------------------------------------------
ALTER TYPE game_status ADD VALUE IF NOT EXISTS 'cancelled';

-- ------------------------------------------------------------
-- 2. New enums
-- ------------------------------------------------------------
CREATE TYPE tournament_format AS ENUM ('single_elimination', 'swiss');

CREATE TYPE tournament_status AS ENUM ('open', 'ready', 'started', 'ended');

CREATE TYPE tournament_round_status AS ENUM ('pending', 'active', 'completed');

CREATE TYPE tournament_match_mode AS ENUM ('full', 'light');

CREATE TYPE tournament_match_status AS ENUM ('pending', 'reported', 'confirmed');

-- ------------------------------------------------------------
-- 3. tournaments
-- ------------------------------------------------------------
CREATE TABLE tournaments (
  id                    bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at            timestamp with time zone DEFAULT now() NOT NULL,
  updated_at            timestamp with time zone DEFAULT now() NOT NULL,
  name                  text NOT NULL,
  address               text NOT NULL,
  date                  timestamp with time zone NOT NULL,
  format                tournament_format NOT NULL,
  status                tournament_status NOT NULL DEFAULT 'open',
  price                 numeric(10, 2),                          -- NULL = free
  description           text,
  registration_deadline timestamp with time zone,
  organizer             uuid NOT NULL REFERENCES users (id) ON UPDATE CASCADE ON DELETE CASCADE,
  community             bigint REFERENCES communities (id) ON UPDATE CASCADE ON DELETE SET NULL
);

ALTER TABLE tournaments ENABLE ROW LEVEL SECURITY;

CREATE POLICY "all" ON tournaments
  AS PERMISSIVE FOR ALL TO authenticated
  USING (true) WITH CHECK (true);

-- ------------------------------------------------------------
-- 4. tournament_registrations
-- ------------------------------------------------------------
CREATE TABLE tournament_registrations (
  id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at    timestamp with time zone DEFAULT now() NOT NULL,
  tournament    bigint NOT NULL REFERENCES tournaments (id) ON UPDATE CASCADE ON DELETE CASCADE,
  "user"        uuid NOT NULL REFERENCES users (id) ON UPDATE CASCADE ON DELETE CASCADE,
  army          bigint NOT NULL REFERENCES armies (id) ON UPDATE CASCADE ON DELETE RESTRICT,
  UNIQUE (tournament, "user")
);

ALTER TABLE tournament_registrations ENABLE ROW LEVEL SECURITY;

CREATE POLICY "all" ON tournament_registrations
  AS PERMISSIVE FOR ALL TO authenticated
  USING (true) WITH CHECK (true);

-- ------------------------------------------------------------
-- 5. tournament_rounds
-- ------------------------------------------------------------
CREATE TABLE tournament_rounds (
  id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at    timestamp with time zone DEFAULT now() NOT NULL,
  tournament    bigint NOT NULL REFERENCES tournaments (id) ON UPDATE CASCADE ON DELETE CASCADE,
  round_number  smallint NOT NULL,
  status        tournament_round_status NOT NULL DEFAULT 'pending',
  UNIQUE (tournament, round_number)
);

ALTER TABLE tournament_rounds ENABLE ROW LEVEL SECURITY;

CREATE POLICY "all" ON tournament_rounds
  AS PERMISSIVE FOR ALL TO authenticated
  USING (true) WITH CHECK (true);

-- ------------------------------------------------------------
-- 6. tournament_matches
-- ------------------------------------------------------------
CREATE TABLE tournament_matches (
  id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at      timestamp with time zone DEFAULT now() NOT NULL,
  updated_at      timestamp with time zone DEFAULT now() NOT NULL,
  round           bigint NOT NULL REFERENCES tournament_rounds (id) ON UPDATE CASCADE ON DELETE CASCADE,
  player_one      uuid NOT NULL REFERENCES users (id) ON UPDATE CASCADE ON DELETE RESTRICT,
  player_two      uuid NOT NULL REFERENCES users (id) ON UPDATE CASCADE ON DELETE RESTRICT,
  player_one_score integer,
  player_two_score integer,
  winner          uuid REFERENCES users (id) ON UPDATE CASCADE ON DELETE RESTRICT,
  mode            tournament_match_mode,
  status          tournament_match_status NOT NULL DEFAULT 'pending',
  game            bigint REFERENCES games (id) ON UPDATE CASCADE ON DELETE SET NULL  -- only set when mode = 'full'
);

ALTER TABLE tournament_matches ENABLE ROW LEVEL SECURITY;

CREATE POLICY "all" ON tournament_matches
  AS PERMISSIVE FOR ALL TO authenticated
  USING (true) WITH CHECK (true);

-- ------------------------------------------------------------
-- 7. Trigger: keep updated_at current on tournament_matches
-- ------------------------------------------------------------
CREATE OR REPLACE FUNCTION update_tournament_match_time()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$;

CREATE TRIGGER update_tournament_match_time
  BEFORE UPDATE ON tournament_matches
  FOR EACH ROW
  EXECUTE FUNCTION update_tournament_match_time();

-- ------------------------------------------------------------
-- 8. Trigger: keep updated_at current on tournaments
-- ------------------------------------------------------------
CREATE OR REPLACE FUNCTION update_tournament_time()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$;

CREATE TRIGGER update_tournament_time
  BEFORE UPDATE ON tournaments
  FOR EACH ROW
  EXECUTE FUNCTION update_tournament_time();

-- ------------------------------------------------------------
-- 9. Trigger: enforce tournament status transitions
--    Allowed transitions:
--      open    → ready    ✓
--      ready   → open     ✓ (reversible)
--      ready   → started  ✓
--      started → ended    ✓
--    Forbidden:
--      started → open     ✗
--      started → ready    ✗
--      ended   → *        ✗
-- ------------------------------------------------------------
CREATE OR REPLACE FUNCTION enforce_tournament_status_transition()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
  -- No-op if status didn't change
  IF NEW.status = OLD.status THEN
    RETURN NEW;
  END IF;

  -- Once started, can only move to ended
  IF OLD.status = 'started' AND NEW.status <> 'ended' THEN
    RAISE EXCEPTION
      'Cannot transition tournament status from started to %. Once started, a tournament can only be ended.',
      NEW.status;
  END IF;

  -- Once ended, no further transitions allowed
  IF OLD.status = 'ended' THEN
    RAISE EXCEPTION
      'Cannot transition tournament status from ended. The tournament is finished.';
  END IF;

  RETURN NEW;
END;
$$;

CREATE TRIGGER enforce_tournament_status_transition
  BEFORE UPDATE OF status ON tournaments
  FOR EACH ROW
  EXECUTE FUNCTION enforce_tournament_status_transition();
